project:
  type: website

website:
  title: "DevOps For Data Science"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: EDA
        href: eda.qmd
      - text: Model
        href: model.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



